### ISSUE TITLE
New version  - issue Rendering issue with fillcolor="null"

### ISSUE THREAD

**Issue by diogo10** [siggijons/graph-untangler-plugin#7]
Hi Siggi, thanks for this repository. Nice work! 

Did you have plans to push a new version so it covers this PR?  https://github.com/siggijons/graph-untangler-plugin/pull/4
I tried it out with version 0.0.4 and I still get the fillcolor="null" on the .gv file.

**Comment by SimonMarquis** [comment]
@siggijons are there new features or fixes that you wanted to include before publishing a new release with this fix? https://github.com/siggijons/graph-untangler-plugin/commit/fe4bbddfbcb793e3fac7a134a4f731a7b2d8d98a

**Comment by siggijons** [comment]
@diogo10 @SimonMarquis I'm sorry for letting this fall through the cracks. I just published a new version v0.0.5 with the latest changes. Please give it a try and let me know if things check out.
